os: Visual Studio 2015
init:
  - git config --global core.autocrlf input

build_script: 
  - cmd: build.bat
  - ps: .\appveyor.ps1

test: off
version: '{build}'
artifacts:
  - path: lib\release
    name: release
  - path: lib\release\*.nupkg
